name: pvPerks
main: com.purityvanilla.pvperks.PVPerks
version: 1.0
api-version: 1.20
authors: [chiralpenguin]
description: Chat plugin for the Purity Vanilla Minecraft server
folia-supported: true
depend: [pvLib, pvCore]
commands:
  joindate:
    description: See when a player first joined the server
    usage: /joindate [player]
    permissions: pvperks.joindate
    aliases: [jd, firstjoin]
  playtime:
    description: See a player's total playtime on the server
    usage: /playtime [player]
    permission: pvperks.playtime
  reload:
    description: Reloads the plugin's configs and messages
    usage: /pvperks-reload
    permission: pvperks.reload
  seen:
    description: See when a player was last online
    usage: /seen <player>
    permission: pvperks.seen
    aliases: [ lastseen ]
permissions:
  pvperks.formatcodes.anvil.all:
    description: Gives access to all formatting codes in anvils
  pvperks.formatcodes.anvil.magic:
    description: Gives access to magic (obfuscated) formatting in anvils
  pvperks.formatcodes.sign.all:
    description: Gives access to all formatting codes in signs
  pvperks.formatcodes.sign.magic:
    description: Gives access to magic (obfuscated) formatting in signs
